export const adminPath = {
  signin: "signin",
  meeting: "meeting",
  feedback: "feedback",
  settings: "settings",
  dashboard: "dashboard",
  userManage: "user-manage",
  courseManage: "course-manage",
  bannerManage: "banner-manage",
  serviceManage: "service-manage",
  projectManage: "project-manage",
};

export const userPath = {
  home: "/",
  login: "/login",
  about: "/about",
  course: "/course",
  service: "/service",
  contact: "/contact",
  library: "/library",
  profile: "/profile",
  register: "/register",
  messages: "/messages",
  resetOTP: "/reset-otp",
  registerOTP: "/register-otp",
  courseDetail: "/course-detail",
  resetPassword: "/reset-password",
  forgotPassword: "/forgot-password",
};
